## traefik.yml

# Docker configuration backend
providers:
  docker:
    defaultRule: "Host(`{{ trimPrefix `/` .Name }}.localhost`)"
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

# API and dashboard configuration
api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
